### ISSUE TITLE
Session has expired.

### ISSUE THREAD

**Issue by freakypie** [mrooney/mintapi#78] opened 2016-06-24 05:49 UTC
I get an exception when i try to get accounts:

Could not parse account data: `<error><code>1</code><description>Session has expired.</description><name></name><type></type></error>`

```
File "./accounts/views.py" in fetchraw
    73.             print(mint.get_accounts())
File "./venv/lib/python2.7/site-packages/mintapi/api.py" in get_accounts
    171.             raise Exception('Could not parse account data: ' + response)
```

**Comment by axerio** [comment] 2016-07-01 19:12
Same for me. Any insight as to why this is happening?

**Comment by phillips199** [comment] 2016-07-03 15:55
+1

**Comment by ScouserInTrousers** [comment] 2016-07-06 01:58
+1

**Comment by FarhadGSRX** [comment] 2016-07-13 02:02
+1

**Comment by canada4663** [comment] 2016-07-16 19:36
+1

**Comment by burnsy89** [comment] 2016-07-20 13:24
+1

**Comment by teamcoltra** [comment] 2016-07-22 21:17
This is a duplicate of #73

**Comment by JosiahParry** [comment] 2016-08-09 19:35
+1

**Comment by mrooney** [comment] 2016-11-20 04:31
Merged a PR and updated the README, now has instructions for the relevant cookies!

**Closed by mrooney** 2016-11-20 04:31 UTC
