### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by ericbiewener** [mrooney/mintapi#51] opened 2015-12-01 16:55 UTC
I'm getting the error "Exception: Mint.com login failed[1]". My code:

```python
import mintapi

email = 'my_email'
password = 'my_password'

mint = mintapi.Mint(email, password)
```

The full traceback of the error is:

```
Traceback (most recent call last):
  File "/Users/ericbiewener/Google Drive/Personal/Dev/ππ Misc/mint/mintapi.py", line 8, in <module>
    mint = mintapi.Mint(email, pw)
  File "/Users/ericbiewener/Google Drive/Personal/Dev/ππ Misc/mint/mintapi/api.py", line 47, in __init__
    self.login_and_get_token(email, password)
  File "/Users/ericbiewener/Google Drive/Personal/Dev/ππ Misc/mint/mintapi/api.py", line 119, in login_and_get_token
    raise Exception('Mint.com login failed[1]')
Exception: Mint.com login failed[1]
```

I get the same error when trying to connect via the command line `mintapi` command.

**Comment by nickpdiana** [comment] 2016-01-29 15:34
Not sure if this is the real problem, but I was getting the same error and suspected it might be due to the special characters I used in my password. I changed my password and used a URL friendly special character: - (hyphen)

This seemed to solve my problem.

**Comment by mrooney** [comment] 2016-02-11 18:37
Interesting, maybe we are not encoding passwords correctly. @ericbiewener, obviously you don't need to tell us your password, but could you share any special/odd characters that might be in it? Then I can try to reproduce by changing my password, and fixing it :)

**Comment by ericbiewener** [comment] 2016-02-21 21:01
It's working now, event with special characters in my password. I might have changed my password since I tried last, not sure if that would have had any effect.

**Comment by mrooney** [comment] 2016-03-04 19:33
Thanks, I'll close this, let me know if you encounter any other issues :)

**Closed by mrooney** 2016-03-04 19:33 UTC
