### ISSUE TITLE
Challenge Required

### ISSUE THREAD

**Issue by Andreilys** [mrooney/mintapi#112] opened 2017-09-13 15:07 UTC
I'm getting an exception raised once in a while when running my script:

   raise MintException('Challenge required, please log in to Mint.com manually and complete the captcha.')
mintapi.api.MintException: Challenge required, please log in to Mint.com manually and complete the captcha.

However, if I keep running my script eventually it will go through. I think a potential solution would be to rerun the script whenever the challenge required exception is raised (or any other ones), only problem I can see is it turns into an infinite loop however from the small testing i've done it seems that it goes through.

```
result = None
while result is None:
    try:
         mint = mintapi.Mint("", "", "", "")
         result = True
    except:
         pass
```

Would an implementation like this make sense in the mintapi project so we can abstract away the hacky-ness of my solution?

**Comment by mrooney** [comment] 2017-09-13 17:22
That's very odd! Could you please contribute this to the discussion at #110 which this is a duplicate of?

**Closed by mrooney** 2017-09-13 17:22 UTC
